train:
  seq_length: 256
  epochs: 1
  total_steps: 10000
  batch_size: 2
  checkpoint_interval: 100
  eval_interval: 100
  pipeline: "GLMPipeline"
  trainer: "AcceleratePPOTrainer"
  tracker: "tensorboard"
  logging_dir: "tensorboard"

model:
  model_path: "/root/autodl-tmp/Data/models/glm-350M-chinese"
  num_layers_unfrozen: -1
  model_arch_type: "seq2seq"

tokenizer:
  tokenizer_path: "/root/autodl-tmp/Data/models/glm-350M-chinese"
  padding_side: "left"

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.01

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000
    eta_min: 5.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 2
  chunk_size: 1
  ppo_epochs: 1
  init_kl_coef: 0.1
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.2
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 5
    top_k: 50
    top_p: 0.8
    do_sample: True
    temperature: 1.0