command_file: null
commands: null
compute_environment: LOCAL_MACHINE
deepspeed_config:
<<<<<<< HEAD
  deepspeed_config_file: configs/ds_config_trlx_gptj_summarize.json
=======
  deepspeed_config_file: configs/ds_config_trlx_pangu.json
>>>>>>> 8d9fb60e1075f1df94c7bdd1fd1d8bb2c4440bb1
  zero3_init_flag: false
distributed_type: DEEPSPEED
downcast_bf16: 'no'
dynamo_backend: 'NO'
fsdp_config: {}
gpu_ids: null
machine_rank: 0
main_process_ip: null
main_process_port: null
main_training_function: main
megatron_lm_config: {}
num_machines: 1
num_processes: 1
rdzv_backend: static
same_network: true
tpu_name: null
tpu_zone: null
use_cpu: false
