train:
  seq_length: 512
  epochs: 5
  total_steps: 500000
  batch_size: 4

  checkpoint_interval: 10000
  eval_interval: 200

  pipeline: "PromptPipeline"
  orchestrator: "PPOOrchestrator"
  trainer: "AcceleratePPOTrainer"

model:
  model_path: ""
  num_layers_unfrozen: 4

tokenizer:
  tokenizer_path: "gpt2"
  truncation_side: "right"

optimizer:
  name: "adamw"
  kwargs:
    lr: 5.0e-6
    betas: [0.9, 0.999]
    eps: 1.0e-8
    weight_decay: 0.01

scheduler:
  name: "cosine_annealing"
  kwargs:
    T_max: 100000
    eta_min: 5.0e-6

method:
  name: "ppoconfig"
  num_rollouts: 4096
  chunk_size: 64
  ppo_epochs: 4
  init_kl_coef: 0.1
  target: 6
  horizon: 10000
  gamma: 1
  lam: 0.95
  cliprange: 0.2
  cliprange_value: 0.2
  vf_coef: 0.2
  scale_reward: False
  ref_mean: null
  ref_std: null
  cliprange_reward: 10
  gen_kwargs:
    max_new_tokens: 100
    top_k: 0.0
    top_p: 0.9
    do_sample: True
    temperature: 1.0